const badges = [
  {
    "id": "fully-hand-crafted",
    "name": "Fully hand-crafted",
    "color": "green",
    "description": "This code is fully hand-made.",
    "longDescription": "Use this badge when your project was written entirely by hand without any AI assistance. It signals that every line of code was authored by a human.",
    "usage": "Add this to your README if you want to emphasize your commitment to human-only craftsmanship."
  },
  {
    "id": "partially-generated",
    "name": "Partially generated",
    "color": "orange",
    "description": "This code is partially generated by an LLM. Some of it is hand-made.",
    "longDescription": "This badge is for projects where AI played a supportive role. Maybe you used an AI to generate boilerplate, refactor functions, or write tests, but you still did the heavy lifting.",
    "usage": "Ideal for projects where AI acted as a pair programmer."
  },
  {
    "id": "content-hand-crafted",
    "name": "Content is hand-crafted",
    "color": "yellow",
    "description": "The code for this project is partially generated by an LLM, but the content (e.g., blog posts) are hand-crafted by a human.",
    "longDescription": "Best for sites (like blogs or documentation) where the infrastructure or technical foundation was built with AI help, but the actual content remains distinctly human-written.",
    "usage": "Use this for AI-assisted websites or static sites."
  },
  {
    "id": "fully-generated",
    "name": "Fully generated",
    "color": "red",
    "description": "This project is fully generated by an LLM.",
    "longDescription": "Use this badge for experiments or projects created almost entirely through LLM prompting. It is a badge of transparency for AI-native code.",
    "usage": "Great for demos, rapid prototypes, or AI experiments."
  }
];
