const badges = [
  {
    "id": "fully-hand-crafted",
    "name": "Fully hand-crafted",
    "color": "green",
    "description": "This code is fully hand-made.",
    "longDescription": "This badge indicates that the project is 100% human-authored. No AI tools, LLM-based autocomplete, or machine-generated boilerplate have been used in the creation of this codebase. It represents a commitment to traditional software engineering practices and human-centered design.",
    "usage": "Use this on repositories where you want to highlight the absence of AI, perhaps for educational purposes, security-critical systems, or as a statement of personal craftsmanship."
  },
  {
    "id": "partially-generated",
    "name": "Partially generated",
    "color": "orange",
    "description": "This code is partially generated by an LLM. Some of it is hand-made.",
    "longDescription": "This badge is for hybrid projects. AI was utilized as a tool—for instance, to generate unit tests, scaffold components, or debug complex issues—but the core architectural decisions, logic flow, and final code quality remain under human control and responsibility.",
    "usage": "Perfect for modern professional projects where AI is used as a productivity booster, pair programmer, or coding assistant."
  },
  {
    "id": "content-hand-crafted",
    "name": "Content is hand-crafted",
    "color": "yellow",
    "description": "The code for this project is partially generated by an LLM, but the content (e.g., blog posts) are hand-crafted by a human.",
    "longDescription": "Specifically tailored for digital garden websites, blogs, or content-heavy platforms. The technical infrastructure (site generator config, CSS frameworks, scripts) may be AI-assisted, but the actual intellectual content—your articles, essays, and stories—is written by a human.",
    "usage": "Use this for blogs, portfolios, or documentation sites where the 'voice' and content are human, even if the tech stack is AI-assisted."
  },
  {
    "id": "fully-generated",
    "name": "Fully generated",
    "color": "red",
    "description": "This project is fully generated by an LLM.",
    "longDescription": "This badge denotes projects that are essentially AI-native, generated end-to-end through prompt engineering. These projects prioritize speed, exploration, and the capabilities of the model over human-maintained codebases. It provides full transparency about the automated origin of the project.",
    "usage": "Ideal for rapid prototypes, AI creative experiments, auto-generated boilerplate, or proof-of-concept projects where code maintainability is not the primary goal."
  }
];
